name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Установка Java (Gradle требует JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # Дать права на выполнение Gradle wrapper
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Сборка проекта и запуск тестов
      - name: Build with Gradle
        run: ./gradlew build

      # Сборка debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Загрузка APK как артефакта
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Сборка release APK (без подписи)
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Загрузка release APK как артефакта
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
